Repository Apexal/late, pull requests merged in 2019-02, with the labels that each got.

#215 Admin Control Panel
  server/api/students/index.js
  server/api/students/students.controller.js
  server/api/students/students.model.js
  src/components/TheHeader.vue
  src/components/admin/AdminStudentList.vue
  src/components/admin/AdminStudentListOverview.vue
  src/router.js
  src/views/TheHomePage.vue
  src/views/admin/TheAdminPage.vue
Labels: back end, database, enhancement, front end

#240 Assignments Group by Course/Due Date
  src/store/modules/work.js
  src/views/assignments/Assignments.vue
  src/views/assignments/AssignmentsUpcoming.vue
Labels: enhancement, front end

#235 ProgressBar
  server/api/assignments/assignments.controller.js
  server/api/assignments/assignments.model.js
  src/components/AssessmentOverviewWorkSchedule.vue
Labels: api, enhancement, front end
